# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f117c69144fb62b2dea7cf33f49d5797f6ed2bceb2ec08d9174ba0f2af1cfc775388cd54a9f539e896c286fe449117039db8f503294730615a35725ea5c68d9

test:
  secret_key_base: 0de12806c91ea44f44331ee65c210c0d86dd5400e3c8338bdf909c00ff425d652497b5b5aec7ebc5e2b9a6d5a49665aa7da258e0d3cff41db2629c01302d0ae4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
